<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="FB_AttributeTest" Id="{957860c0-06d0-4a53-9b3d-b3dab5789371}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'some_made_up_key':='some_made_up_value'}
FUNCTION_BLOCK FB_AttributeTest
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_AttributeTest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>