<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="WriteTest" Id="{9210e4e8-d22e-4964-823b-6bbbee7e173c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK WriteTest
VAR
	// Writable targets — PLC never modifies these, Go test owns them
	bool_var : BOOL;
	sint_var : SINT;
	usint_var : USINT;
	byte_var : BYTE;
	int_var : INT;
	uint_var : UINT;
	word_var : WORD;
	dint_var : DINT;
	udint_var : UDINT;
	dword_var : DWORD;
	lint_var : LINT;
	ulint_var : ULINT;
	lword_var : LWORD;
	real_var : REAL;
	lreal_var : LREAL;
	time_var : TIME;
	tod_var : TOD;
	date_var : DATE;
	dt_var : DT;
	//ltime_var : LTIME;
	//ltod_var : LTOD;
	//ldate_var : LDATE;
	//ldt_var : LDT;
	string_var : STRING(255);
	struct_var : TypeTestStruct;
	int_array : ARRAY[0..9] OF INT;
	dint_array : ARRAY[0..9] OF DINT;
	int_array_2d : ARRAY[0..2, 0..2] OF INT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="WriteTest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>